name: Hydra Session Chain

on:
  workflow_dispatch:

jobs:
  start-session:
    runs-on: ubuntu-latest
    
    # This tells the job to use your pre-built Kali image from Docker Hub
    container:
      image: docker://${{ secrets.DOCKERHUB_USERNAME }}/kali-rdp-image:latest
      options: --ipc=host

    steps:
      - name: 1. Install Tools & Mount Storage
        run: |
          # The OS is already Kali, but we need to install a few tools for the workflow
          apt-get update
          apt-get install -y curl jq rclone --no-install-recommends
          
          # Decode the rclone config from secrets
          mkdir -p /root/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 --decode > /root/.config/rclone/rclone.conf
          
          # Create mount points and mount the cloud drive
          mkdir -p /home/persistent_storage
          nohup rclone mount my_drive: /home/persistent_storage --allow-other --vfs-cache-mode writes &
          sleep 5

      - name: 2. Start RDP and Show Connection Details
        run: |
          # Start the XRDP service that is already inside the container
          /usr/sbin/xrdp-sesman
          /usr/sbin/xrdp -n
          
          # Install and start ngrok tunnel
          apt-get update && apt-get install -y ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
          nohup ngrok tcp 3389 &
          sleep 5
          
          # Get the URL from the ngrok API
          RDP_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
          
          # --- SIMPLE METHOD: PRINT DETAILS CLEARLY IN THE LOG ---
          echo "********************************************************************"
          echo "********************************************************************"
          echo ""
          echo "      ✅ Your Kali RDP Connection is Ready!"
          echo ""
          echo "      RDP Address: ${RDP_URL}"
          echo "      Username:    root"
          echo "      Password:    the one you set in your Dockerfile"
          echo ""
          echo "********************************************************************"
          echo "********************************************************************"

      - name: 3. The Hydra Chain Trigger
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Session is live. Triggering the next job in ~5 hours 45 minutes."
          sleep 20700
          
          echo "Spawning new Hydra head..."
          # Use GitHub API to trigger this same workflow again, creating the chain
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/hydra-chain.yml/dispatches" \
            -d '{"ref":"main"}'
